ALTER TABLE categoria ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT true;
ALTER TABLE marca ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT true;
ALTER TABLE producto ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT true;
